//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.08 at 04:23:51 PM EEST 
//


package bg.duosoft.bpo.patent_classification.be.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;div xmlns="http://www.wipo.int/classifications/ipc/masterfiles" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;interval references to IPC symbols&lt;/div&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for mref complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mref">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.wipo.int/classifications/ipc/masterfiles}sref">
 *       &lt;attribute name="endRef" use="required" type="{http://www.wipo.int/classifications/ipc/masterfiles}symbol" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mref")
public class Mref
    extends Sref
{

    @XmlAttribute(name = "endRef", required = true)
    protected String endRef;

    /**
     * Gets the value of the endRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndRef() {
        return endRef;
    }

    /**
     * Sets the value of the endRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndRef(String value) {
        this.endRef = value;
    }

    @Override
    public String toString() {
        return endRef + ' ' + ref;
    }
}
