//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.08 at 04:23:51 PM EEST 
//


package bg.duosoft.bpo.patent_classification.be.jaxb;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IPCScheme_QNAME = new QName("http://www.wipo.int/classifications/ipc/masterfiles", "IPCScheme");
    private final static QName _SchemeTextU_QNAME = new QName("http://www.wipo.int/classifications/ipc/masterfiles", "u");
    private final static QName _SchemeTextSref_QNAME = new QName("http://www.wipo.int/classifications/ipc/masterfiles", "sref");
    private final static QName _SchemeTextMref_QNAME = new QName("http://www.wipo.int/classifications/ipc/masterfiles", "mref");
    private final static QName _SchemeTextSub_QNAME = new QName("http://www.wipo.int/classifications/ipc/masterfiles", "sub");
    private final static QName _SchemeTextImg_QNAME = new QName("http://www.wipo.int/classifications/ipc/masterfiles", "img");
    private final static QName _SchemeTextSup_QNAME = new QName("http://www.wipo.int/classifications/ipc/masterfiles", "sup");
    private final static QName _SchemeNoteParagraphReferences_QNAME = new QName("http://www.wipo.int/classifications/ipc/masterfiles", "references");
    private final static QName _SchemeNoteParagraphOrphan_QNAME = new QName("http://www.wipo.int/classifications/ipc/masterfiles", "orphan");
    private final static QName _SchemeNoteParagraphSubnote_QNAME = new QName("http://www.wipo.int/classifications/ipc/masterfiles", "subnote");
    private final static QName _SchemeNoteParagraphText_QNAME = new QName("http://www.wipo.int/classifications/ipc/masterfiles", "text");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IPCScheme }
     * 
     */
    public IPCScheme createIPCScheme() {
        return new IPCScheme();
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSub() {
        return new Sub();
    }

    /**
     * Create an instance of {@link Img }
     * 
     */
    public Img createImg() {
        return new Img();
    }

    /**
     * Create an instance of {@link SchemeTextBody }
     * 
     */
    public SchemeTextBody createSchemeTextBody() {
        return new SchemeTextBody();
    }

    /**
     * Create an instance of {@link SchemeEntryReference }
     * 
     */
    public SchemeEntryReference createSchemeEntryReference() {
        return new SchemeEntryReference();
    }

    /**
     * Create an instance of {@link Underline }
     * 
     */
    public Underline createUnderline() {
        return new Underline();
    }

    /**
     * Create an instance of {@link SchemeText }
     * 
     */
    public SchemeText createSchemeText() {
        return new SchemeText();
    }

    /**
     * Create an instance of {@link SchemeTitle }
     * 
     */
    public SchemeTitle createSchemeTitle() {
        return new SchemeTitle();
    }

    /**
     * Create an instance of {@link Sup }
     * 
     */
    public Sup createSup() {
        return new Sup();
    }

    /**
     * Create an instance of {@link SchemeNote }
     * 
     */
    public SchemeNote createSchemeNote() {
        return new SchemeNote();
    }

    /**
     * Create an instance of {@link SchemeOrphan }
     * 
     */
    public SchemeOrphan createSchemeOrphan() {
        return new SchemeOrphan();
    }

    /**
     * Create an instance of {@link SchemeTitlePart }
     * 
     */
    public SchemeTitlePart createSchemeTitlePart() {
        return new SchemeTitlePart();
    }

    /**
     * Create an instance of {@link SchemeReferences }
     * 
     */
    public SchemeReferences createSchemeReferences() {
        return new SchemeReferences();
    }

    /**
     * Create an instance of {@link SchemeNoteParagraph }
     * 
     */
    public SchemeNoteParagraph createSchemeNoteParagraph() {
        return new SchemeNoteParagraph();
    }

    /**
     * Create an instance of {@link SchemeSubNote }
     * 
     */
    public SchemeSubNote createSchemeSubNote() {
        return new SchemeSubNote();
    }

    /**
     * Create an instance of {@link SchemeIndex }
     * 
     */
    public SchemeIndex createSchemeIndex() {
        return new SchemeIndex();
    }

    /**
     * Create an instance of {@link IpcEntry }
     * 
     */
    public IpcEntry createIpcEntry() {
        return new IpcEntry();
    }

    /**
     * Create an instance of {@link Sref }
     * 
     */
    public Sref createSref() {
        return new Sref();
    }

    /**
     * Create an instance of {@link Mref }
     * 
     */
    public Mref createMref() {
        return new Mref();
    }

    /**
     * Create an instance of {@link SchemeIndexEntry }
     * 
     */
    public SchemeIndexEntry createSchemeIndexEntry() {
        return new SchemeIndexEntry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IPCScheme }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "IPCScheme")
    public JAXBElement<IPCScheme> createIPCScheme(IPCScheme value) {
        return new JAXBElement<IPCScheme>(_IPCScheme_QNAME, IPCScheme.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Underline }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "u", scope = SchemeText.class)
    public JAXBElement<Underline> createSchemeTextU(Underline value) {
        return new JAXBElement<Underline>(_SchemeTextU_QNAME, Underline.class, SchemeText.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sref }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "sref", scope = SchemeText.class)
    public JAXBElement<Sref> createSchemeTextSref(Sref value) {
        return new JAXBElement<Sref>(_SchemeTextSref_QNAME, Sref.class, SchemeText.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mref }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "mref", scope = SchemeText.class)
    public JAXBElement<Mref> createSchemeTextMref(Mref value) {
        return new JAXBElement<Mref>(_SchemeTextMref_QNAME, Mref.class, SchemeText.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sub }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "sub", scope = SchemeText.class)
    public JAXBElement<Sub> createSchemeTextSub(Sub value) {
        return new JAXBElement<Sub>(_SchemeTextSub_QNAME, Sub.class, SchemeText.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Img }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "img", scope = SchemeText.class)
    public JAXBElement<Img> createSchemeTextImg(Img value) {
        return new JAXBElement<Img>(_SchemeTextImg_QNAME, Img.class, SchemeText.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "sup", scope = SchemeText.class)
    public JAXBElement<Sup> createSchemeTextSup(Sup value) {
        return new JAXBElement<Sup>(_SchemeTextSup_QNAME, Sup.class, SchemeText.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sref }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "sref", scope = SchemeReferences.class)
    public JAXBElement<Sref> createSchemeReferencesSref(Sref value) {
        return new JAXBElement<Sref>(_SchemeTextSref_QNAME, Sref.class, SchemeReferences.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mref }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "mref", scope = SchemeReferences.class)
    public JAXBElement<Mref> createSchemeReferencesMref(Mref value) {
        return new JAXBElement<Mref>(_SchemeTextMref_QNAME, Mref.class, SchemeReferences.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sref }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "sref", scope = Underline.class)
    public JAXBElement<Sref> createUnderlineSref(Sref value) {
        return new JAXBElement<Sref>(_SchemeTextSref_QNAME, Sref.class, Underline.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mref }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "mref", scope = Underline.class)
    public JAXBElement<Mref> createUnderlineMref(Mref value) {
        return new JAXBElement<Mref>(_SchemeTextMref_QNAME, Mref.class, Underline.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SchemeReferences }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "references", scope = SchemeNoteParagraph.class)
    public JAXBElement<SchemeReferences> createSchemeNoteParagraphReferences(SchemeReferences value) {
        return new JAXBElement<SchemeReferences>(_SchemeNoteParagraphReferences_QNAME, SchemeReferences.class, SchemeNoteParagraph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SchemeOrphan }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "orphan", scope = SchemeNoteParagraph.class)
    public JAXBElement<SchemeOrphan> createSchemeNoteParagraphOrphan(SchemeOrphan value) {
        return new JAXBElement<SchemeOrphan>(_SchemeNoteParagraphOrphan_QNAME, SchemeOrphan.class, SchemeNoteParagraph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SchemeSubNote }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "subnote", scope = SchemeNoteParagraph.class)
    public JAXBElement<SchemeSubNote> createSchemeNoteParagraphSubnote(SchemeSubNote value) {
        return new JAXBElement<SchemeSubNote>(_SchemeNoteParagraphSubnote_QNAME, SchemeSubNote.class, SchemeNoteParagraph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SchemeText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", name = "text", scope = SchemeNoteParagraph.class)
    public JAXBElement<SchemeText> createSchemeNoteParagraphText(SchemeText value) {
        return new JAXBElement<SchemeText>(_SchemeNoteParagraphText_QNAME, SchemeText.class, SchemeNoteParagraph.class, value);
    }

}
