//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.08 at 04:23:51 PM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.wipo.int/classifications/ipc/masterfiles", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bg.duosoft.bpo.patent_classification.be.jaxb;
