//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.08 at 04:23:51 PM EEST 
//


package bg.duosoft.bpo.patent_classification.be.jaxb;

import org.springframework.util.CollectionUtils;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlMixed;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;div xmlns="http://www.wipo.int/classifications/ipc/masterfiles" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;formatted text, also may contain references, symbols and images&lt;/div&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for schemeText complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="schemeText">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{http://www.wipo.int/classifications/ipc/masterfiles}schemeTextContent"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "schemeText", propOrder = {
    "content"
})
@XmlSeeAlso({
    SchemeEntryReference.class
})
public class SchemeText {

    @XmlElementRefs({
        @XmlElementRef(name = "sref", namespace = "http://www.wipo.int/classifications/ipc/masterfiles", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sub", namespace = "http://www.wipo.int/classifications/ipc/masterfiles", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sup", namespace = "http://www.wipo.int/classifications/ipc/masterfiles", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "img", namespace = "http://www.wipo.int/classifications/ipc/masterfiles", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "u", namespace = "http://www.wipo.int/classifications/ipc/masterfiles", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "mref", namespace = "http://www.wipo.int/classifications/ipc/masterfiles", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * 
     * 				
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;div xmlns="http://www.wipo.int/classifications/ipc/masterfiles" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;formatted text, also may contain references, symbols and images&lt;/div&gt;
     * </pre>
     * 
     * 			Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link JAXBElement }{@code <}{@link Sref }{@code >}
     * {@link JAXBElement }{@code <}{@link Sub }{@code >}
     * {@link JAXBElement }{@code <}{@link Sup }{@code >}
     * {@link JAXBElement }{@code <}{@link Img }{@code >}
     * {@link JAXBElement }{@code <}{@link Underline }{@code >}
     * {@link JAXBElement }{@code <}{@link Mref }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        if (!CollectionUtils.isEmpty(content))
        for(Serializable text : content){
            sb.append(text.toString());
            sb.append("; ");
        }
        return sb.toString();
    }
}
