//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.08 at 04:23:51 PM EEST 
//


package bg.duosoft.bpo.patent_classification.be.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;div xmlns="http://www.wipo.int/classifications/ipc/masterfiles" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;text of a structured or non-structured entry&lt;/div&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for schemeTextBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="schemeTextBody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="note" type="{http://www.wipo.int/classifications/ipc/masterfiles}schemeNote"/>
 *         &lt;element name="index" type="{http://www.wipo.int/classifications/ipc/masterfiles}schemeIndex"/>
 *         &lt;element name="title" type="{http://www.wipo.int/classifications/ipc/masterfiles}schemeTitle"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "schemeTextBody", propOrder = {
    "note",
    "index",
    "title"
})
public class SchemeTextBody {

    protected SchemeNote note;
    protected SchemeIndex index;
    protected SchemeTitle title;

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link SchemeNote }
     *     
     */
    public SchemeNote getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemeNote }
     *     
     */
    public void setNote(SchemeNote value) {
        this.note = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link SchemeIndex }
     *     
     */
    public SchemeIndex getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemeIndex }
     *     
     */
    public void setIndex(SchemeIndex value) {
        this.index = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link SchemeTitle }
     *     
     */
    public SchemeTitle getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemeTitle }
     *     
     */
    public void setTitle(SchemeTitle value) {
        this.title = value;
    }

}
