//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.08 at 04:23:51 PM EEST 
//


package bg.duosoft.bpo.patent_classification.be.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;div xmlns="http://www.wipo.int/classifications/ipc/masterfiles" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;text of a single paragraph and its subparagraphs&lt;/div&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;h3 xmlns="http://www.wipo.int/classifications/ipc/masterfiles" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;Structure:&lt;/h3&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;div xmlns="http://www.wipo.int/classifications/ipc/masterfiles" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;two independent cases:&lt;/div&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ul xmlns="http://www.wipo.int/classifications/ipc/masterfiles" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;&lt;li&gt;when parent note type is regular prefixed or non-prefixed (not a 'table'):&lt;br/&gt;&lt;dl&gt;&lt;dt&gt;text&lt;/dt&gt;&lt;dd&gt;contains the text itself&lt;/dd&gt;&lt;dt&gt;subnote&lt;/dt&gt;&lt;dd&gt;sequence of subparagraphs&lt;/dd&gt;&lt;dt&gt;orphan:&lt;/dt&gt;&lt;dd&gt;a subparagraph that falls out of the subparagraph sequence (non-prefixed)&lt;/dd&gt;
 * 						&lt;/dl&gt;
 * 					&lt;/li&gt;&lt;li&gt;when parent note type is 'table' (during the reform: gradually moved to the definitions):&lt;br/&gt;&lt;dl&gt;&lt;dt&gt;references&lt;/dt&gt;&lt;dd&gt;list of references&lt;/dd&gt;&lt;dt&gt;text&lt;/dt&gt;&lt;dd&gt;text associated to references&lt;/dd&gt;
 * 						&lt;/dl&gt;
 * 					&lt;/li&gt;
 * 				&lt;/ul&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for schemeNoteParagraph complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="schemeNoteParagraph">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="text" type="{http://www.wipo.int/classifications/ipc/masterfiles}schemeText"/>
 *           &lt;element name="subnote" type="{http://www.wipo.int/classifications/ipc/masterfiles}schemeSubNote" minOccurs="0"/>
 *           &lt;element name="orphan" type="{http://www.wipo.int/classifications/ipc/masterfiles}schemeOrphan" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="references" type="{http://www.wipo.int/classifications/ipc/masterfiles}schemeReferences"/>
 *           &lt;element name="text" type="{http://www.wipo.int/classifications/ipc/masterfiles}schemeText"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="edition" type="{http://www.wipo.int/classifications/ipc/masterfiles}editionList" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "schemeNoteParagraph", propOrder = {
    "content"
})
public class SchemeNoteParagraph {

    @XmlElementRefs({
        @XmlElementRef(name = "references", namespace = "http://www.wipo.int/classifications/ipc/masterfiles", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "orphan", namespace = "http://www.wipo.int/classifications/ipc/masterfiles", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subnote", namespace = "http://www.wipo.int/classifications/ipc/masterfiles", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "text", namespace = "http://www.wipo.int/classifications/ipc/masterfiles", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> content;
    @XmlAttribute(name = "edition")
    protected String edition;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Text" is used by two different parts of a schema. See: 
     * line 310 of file:/D:/Local%20workspace/ipc_loader/src/main/resources/inc-scheme_3-1.xsd
     * line 278 of file:/D:/Local%20workspace/ipc_loader/src/main/resources/inc-scheme_3-1.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link SchemeOrphan }{@code >}
     * {@link JAXBElement }{@code <}{@link SchemeSubNote }{@code >}
     * {@link JAXBElement }{@code <}{@link SchemeReferences }{@code >}
     * {@link JAXBElement }{@code <}{@link SchemeText }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

    /**
     * Gets the value of the edition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdition() {
        return edition;
    }

    /**
     * Sets the value of the edition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdition(String value) {
        this.edition = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        for(Serializable text : content){
            sb.append(text.toString());
            sb.append("; ");
        }
        sb.append(edition);
        sb.append("; ");
        return sb.toString();
    }

}
