//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.08 at 04:23:51 PM EEST 
//


package bg.duosoft.bpo.patent_classification.be.jaxb;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;div xmlns="http://www.wipo.int/classifications/ipc/masterfiles" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;out-of-sequence subparagraph closing a sentence and rarely opening a new subdivision&lt;/div&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for schemeOrphan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="schemeOrphan">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="text" type="{http://www.wipo.int/classifications/ipc/masterfiles}schemeText"/>
 *         &lt;element name="subnote" type="{http://www.wipo.int/classifications/ipc/masterfiles}schemeSubNote" minOccurs="0"/>
 *         &lt;element name="orphan" type="{http://www.wipo.int/classifications/ipc/masterfiles}schemeOrphan" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="indent" type="{http://www.wipo.int/classifications/ipc/masterfiles}indent" />
 *       &lt;attribute name="edition" type="{http://www.wipo.int/classifications/ipc/masterfiles}editionList" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "schemeOrphan", propOrder = {
    "text",
    "subnote",
    "orphan"
})
public class SchemeOrphan {

    @XmlElement(required = true)
    protected SchemeText text;
    protected SchemeSubNote subnote;
    protected SchemeOrphan orphan;
    @XmlAttribute(name = "indent")
    protected BigInteger indent;
    @XmlAttribute(name = "edition")
    protected String edition;

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link SchemeText }
     *     
     */
    public SchemeText getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemeText }
     *     
     */
    public void setText(SchemeText value) {
        this.text = value;
    }

    /**
     * Gets the value of the subnote property.
     * 
     * @return
     *     possible object is
     *     {@link SchemeSubNote }
     *     
     */
    public SchemeSubNote getSubnote() {
        return subnote;
    }

    /**
     * Sets the value of the subnote property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemeSubNote }
     *     
     */
    public void setSubnote(SchemeSubNote value) {
        this.subnote = value;
    }

    /**
     * Gets the value of the orphan property.
     * 
     * @return
     *     possible object is
     *     {@link SchemeOrphan }
     *     
     */
    public SchemeOrphan getOrphan() {
        return orphan;
    }

    /**
     * Sets the value of the orphan property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemeOrphan }
     *     
     */
    public void setOrphan(SchemeOrphan value) {
        this.orphan = value;
    }

    /**
     * Gets the value of the indent property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndent() {
        return indent;
    }

    /**
     * Sets the value of the indent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndent(BigInteger value) {
        this.indent = value;
    }

    /**
     * Gets the value of the edition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdition() {
        return edition;
    }

    /**
     * Sets the value of the edition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdition(String value) {
        this.edition = value;
    }

}
